mapbox/pbf

- README.md
- bench/bench.html
- bench/bench.js
- index.js
- test/pbf.test.js
Closes #19, ref #20.
1. A different `writeMessage` mechanism that accepts function rather than a `Pbf` instance and leads to huge encoding performance improvement.
2. Replaced `readPacked` and `writePacked` with `readPackedVarint`, etc. for better performance (70% faster decoding in browsers) and simpler API.
While the code is a bit more verbose now, the library size grew from 2.99KB to just 3.12KB gzipped — not much. Now on to the benchmarks:
Node encoding:
```
encode vector tile with pbf x 64.65 ops/sec ±1.52% (60 runs sampled) # before
encode vector tile with pbf x 172 ops/sec ±1.16% (82 runs sampled) # after
```
Browser encoding:
```
encode vector tile 10 times: 154ms # before
encode vector tile 10 times: 38ms # after
```
Browser decoding:
```
decode vector tile 10 times: 75ms # …
```
> Much faster writeMessage and simpler packed API

- README.md
- bench/bench.js
- bench/vector_tile.js
- bin/pbf
- package.json
A Node script that takes a `proto` file and turns it into a JS module for writing and reading `Pbf`. Closes #22. Usage:
```bash
$ pbf vector_tile.proto > vector_tile.js
```
Also accepts `--no-write` and `--no-read` arguments that strip corresponding code.
Generated code looks like this: https://github.com/mapbox/pbf/blob/protoc/bench/vector_tile.js
> Proto to JavaScript compiler

- README.md
- bench/vector_tile.js
- index.js
- test/pbf.test.js
Closes #27, related: https://github.com/mapbox/vector-tile-js/issues/21.
> add readVarint64 method that handles negative int64 values

- index.js
Used various tricks to improve generic runtime performance.
Results on my machine as follows:
- before the change
```
decode vector tile with pbf x 858 ops/sec ±1.17% (90 runs sampled)
encode vector tile with pbf x 556 ops/sec ±1.46% (84 runs sampled)
```
- after the change
```
decode vector tile with pbf x 999 ops/sec ±1.13% (92 runs sampled)
encode vector tile with pbf x 638 ops/sec ±1.48% (84 runs sampled)
```
(both show ~15% improvement)
> Improve reading/writing performance

- bench/vector_tile.js
- bench/vector_tile.proto
- compile.js
- test/compile.test.js
- test/fixtures/defaults.proto
- test/fixtures/defaults_proto3.proto
- test/fixtures/embedded_type.proto
Note: This would be a **breaking** change / **major** revision as it drastically affects the way default values are handled.
According to the [protobuf spec](https://developers.google.com/protocol-buffers/docs/proto3#default), when a message is parsed and it does not contain an element the default value for that type is used.
This commit will provide default for each field type when parsing. In addition, similar to other protobuf encoding implementations, when using `proto3` it will omit fields that are equivalent to the default value.
Omitting default values is only safe in `proto3` because the default value can be overriden in `proto2`.
> Set default values when decoding and omit default values when encoding

- bench/vector_tile.js
- compile.js
- test/compile.test.js
- test/fixtures/defaults_implicit.proto
Follow-up to #42 cc @kjvalencik.
- set `[]` default for packed fields too — this is more consistent with default for non-packed repeated fields, and also improves decoding performance (in my bench from 820 to 880) because all properties are now predefined.
- store defaults in a special `_defaults` object rather than overwriting `options`, which makes it easier to understand the code.
- DRY up the code more
- more tests for implicit defaults
> Follow-up to default improvements

- index.js
- test/pbf.test.js
Resolves https://github.com/mapbox/pbf/issues/52
> Avoid writing an unserializable message by defaulting writeVarint to 0

- compile.js
- test/compile.test.js
- test/fixtures/oneof.proto
Resolves https://github.com/mapbox/pbf/issues/51
Previous generated code:
```js
Envelope.read = function (pbf, end) {
return pbf.readFields(Envelope._readField, {id: 0, int: 0, float: 0, string: ""}, end);
};
Envelope._readField = function (tag, obj, pbf) {
if (tag === 1) obj.id = pbf.readVarint();
else if (tag === 2) obj.int = pbf.readVarint();
else if (tag === 3) obj.float = pbf.readFloat();
else if (tag === 4) obj.string = pbf.readString();
};
```
New generated code:
```js
Envelope.read = function (pbf, end) {
return pbf.readFields(Envelope._readField, {id: 0, int: 0, float: 0, string: ""}, end);
};
Envelope._readField = function (tag, obj, pbf) {
if (tag === 1) obj.id = pbf.readVarint();
else if (tag === 2) obj.int = pbf.readVarint(), obj.value = "int";
else if (tag === 3) obj.float = …
```
> Set oneof value to set field name

- bench/bench-tiles.js
- package.json
I came to the conclusion that the benchmark in `bench/bench.js` doesn’t really make a lot of sense because V8 is extremely good at optimizing stuff that does the same thing over and over.
So I created a much more representative benchmark that downloads (and caches) 439 sample tiles from Mapbox Streets and runs decoding/encoding on them. Here’s a sample result:
```
439 tiles, 22612 KB total
read time: 405ms, or 54 MB/s
write time: 408ms, or 54 MB/s
```
I ran it on all commits between v2.0.1 and master and actually the most impactful change is the defaults PR. This is fine though — e.g. specifically for VT, you can optimize manually by definding a defaults object and then doing `Object.create(defaults)`. This probably doesn’t make sense for the compiler to do though — the performance is …
> Add a real world tiles bench

- README.md
- index.js
- test/pbf.test.js
cc @kjvalencik — just realized it’s now unnecessary after your changes.
> Remove unnecessary readVarint64 method

- index.js
- test/compile.test.js
- test/fixtures/packed_proto3.proto
Resolves https://github.com/mapbox/pbf/issues/66
> Fix packed types with multi-byte tags by storing the last type read

- README.md
using [pbf-loader](https://www.npmjs.com/package/pbf-loader), you can require .proto file that returns the compiled module that you can use directly. This would prevent you from requiring:
- pbf/compile
- protocol-buffers-schema
- fs
Instead, you would:
```
var proto = require('./example.proto');
var Test = proto.Test;
```
> update readme to add pbf-loader (a webpack loader) to require .proto files

- compile.js
- package.json
- test/compile.test.js
- test/fixtures/map.proto
Implements https://github.com/mapbox/pbf/issues/81
> Implement maps

- index.js
- test/pbf.test.js
When writing a packed message the tag is currently always written, even if the array is empty.
> Optimize packed encoding to skip empty arrays

- bench/bench.js
- package.json
I was doing some comparisons on various protocol buffer libraries for JS, and I thought others might benefit from a benchmark comparing pbf and [protobuf.js](https://github.com/dcodeIO/protobuf.js). Pbf seems faster on this data set at encoding, and is on par for decoding. Cheers!
> Add protobuf.js to benchmarks

- test/compile.test.js
- test/fixtures/packed.proto
One of the transitive dependencies (protocol-buffers-schema) got
upgraded, causing some of the compile tests to break, most notably
with this message:
Fields of type MessageType cannot be declared [packed=true]. Only
repeated fields of primitive numeric types (types which use the
varint, 32-bit, or 64-bit wire types) can be declared "packed". See
https://developers.google.com/protocol-buffers/docs/encoding#optional
Remove the `MessageType` enum and use `int32` in its place.
The new version of `protocol-buffers-schema` also changed how enums are
represented in json, breaking another test.
> Fix broken tests

- README.md
- index.js
- package.json
- test/pbf.test.js
This fixes a data corruption bug when writing a message that exceeds
0x10000000 bytes in size. The varint-encoded size in the beginning of
the message includes an extra byte.
Add a test for this condition.
> Fix a corruption when raw message > 0x10000000 bytes

- compile.js
With this patch, `exports` will be added to result code, even if `--no-read` option is used.
Fixes #98
> Fix #98: keep `exports` with `--no-read` option

- index.js
Currently `readUtf8` is both slow in terms of ops/s and retains excessive amounts of memory when reading long strings (long being experimentally found to be more than 12 bytes).
This PR adds a heuristic to use the built-in browser TextDecoder API in the case of these long strings, which improves ops/s and also memory retention (avoids the usage of sophisticated concatenated string data structures based on trees of pointers).
Closes #106. cc @dcervelli
> Fix utf8 read peformance

- compile.js
- test/compile.test.js
This fixes the typescript type errors in #107 and just makes more sense if you ask me.
> Use undefined instead of null as the default value

- index.js
The default for TextDecoder is the format 'utf-8'. In my project I'm also using the library @auth0/auth0-spa-js, which loads the polyfill fast-text-encoding for TextDecoder. This polyfilled version will throw an error if it gets passed 'utf8'. This causes my app to crash on Edge.
alternatives:
- remove the argument, it'll default to utf-8.
- wrap the initializer in a try/catch
> add dash in utf-8

- compile.js
- test/compile.test.js
- test/fixtures/type_string.proto
This adds support for the jstype option.
When a field (integer or floating number) has the jstype option set to JS_STRING, it will be converted to and from string.
All the changes happen at compile time, so it should not break any application, nor increase the size of the application.
> added support for js_type at compile time
